site_name: YCombinator-Scraper
site_description: A Python command-line tool and package for scraping company, job, and founder data from Workatastartup.com.
site_url: https://nneji123.github.io/ycombinator-scraper

theme:
  name: material
  # custom_dir: docs/overrides
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.svg
  favicon: img/logo.png

  features:
    - content.action.edit
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - navigation.expand
    - navigation.footer
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky

repo_name: Nneji123/ycombinator-scraper
repo_url: https://github.com/Nneji123/ycombinator-scraper
edit_uri: ""

nav:
  - Home: index.md
  - Installation Guide: installation.md
  - Configuration: configuration.md
  - Usage:
    - CLI: usage/cli.md
    - Examples: usage/examples.md
    - Package: usage/package.md
  - API Reference: api_reference.md
  - CLI Reference: cli_reference.md
  - Changelog: changelog.md
  - License: license.md




markdown_extensions:
  # Built-in
  - markdown.extensions.abbr:
  - markdown.extensions.admonition:
  - markdown.extensions.attr_list:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - markdown.extensions.meta:
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      permalink: true
  # Extra
  - mkdocs-click:
  - pymdownx.arithmatex:
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.details:
  - pymdownx.emoji:
      # https://github.com/twitter/twemoji
      # https://raw.githubusercontent.com/facelessuser/pymdown-extensions/master/pymdownx/twemoji_db.py
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: false
      linenums_style: pymdownx-inline
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.keys:
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shortener: true
      social_url_shorthand: true
      normalize_issue_symbols: true
      provider: github
      user: pypa
      repo: ycombinator_scraper
  - pymdownx.mark:
  - pymdownx.progressbar:
  - pymdownx.saneheaders:
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde:


extra:
  # analytics:
  #   provider: google
  #   property: G-T78C5GNRXK
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Nneji123/ycombinator-scraper
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/@neji_14
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ifeanyi-nneji
    - icon: fontawesome/brands/hashnode
      link: https://hashnode.com/Nneji123
    - icon: fontawesome/brands/medium
      link: https://medium.com/@ifeanyi777
    - icon: fontawesome/solid/globe
      link: https://flowcv.me/ifeanyi

# extra_css:
#   - css/termynal.css
#   - css/custom.css

# extra_javascript:
#   - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js
#   - js/termynal.js
#   - js/custom.js
