name: Codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Python Package
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Setup Chrome dependencies
      run: |
          cd .github
          cd scripts
          ./run.sh

    - name: Install requirements
      run: |
        pip install -r requirements-test.txt
        

    - name: Run tests and collect coverage
      run:  |
          echo "${{ secrets.ENV_FILE }}" > .env
          mkdir logs
          pytest --cov=ycombinator_scraper tests --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
