name: Codecov

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Python Package
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Setup Chrome dependencies
      run:  apt-get update && \
            apt-get install -y \
            wget \
            unzip \
            libglib2.0-0 \
            libnss3 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            fonts-liberation \
            libappindicator1 \
            libasound2 \
            libatk-bridge2.0-0 \
            libgtk-3-0  \
            dpkg

    - name: Install Chrome
      run:  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
            apt-get update && apt-get -y install google-chrome-stable


    - name: Install requirements
      run: pip install -r requirements-test.txt

    - name: Run tests and collect coverage
      run: pytest --cov=ycombinator_scraper tests --cov-report=xml
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
